[run]
init_cmds = [
	["go", "build", "-o", "./bin/osgraphql", "./cmds/osgraphql"],
	["./bin/osgraphql"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = []						# Directories to watch
watch_exts = [".toml", ".go"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 15				# Time to wait until force kill
graceful_kill = false				# Wait for exit and before directly kill
cmds = [
	["go", "build", "-o", "./bin/osgraphql", "./cmds/osgraphql"],
	["./bin/osgraphql"]
] # Commands to run

[sync]
listen_addr = ":9000"
remote_addr = ":9000"
